# Generated by Django 4.1.4 on 2022-12-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiredpayments',
            name='penalty_fee_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
