# Generated by Django 4.1.4 on 2022-12-20 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiredpayments',
            name='penalty_fee_amount',
            field=models.FloatField(default=25.0),
        ),
        migrations.AlterField(
            model_name='paymentuser2',
            name='expirationDate',
            field=models.DateField(default='2022-12-18'),
        ),
        migrations.AlterField(
            model_name='paymentuser2',
            name='paymentDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
