# Generated by Django 4.1.4 on 2022-12-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_expiredpayments_penalty_fee_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentuser2',
            name='expirationDate',
            field=models.DateField(),
        ),
    ]
