# Generated by Django 4.1.4 on 2022-12-20 02:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_expiredpayments_penalty_fee_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentuser2',
            name='expirationDate',
            field=models.DateField(default=datetime.date(2022, 12, 18)),
        ),
    ]
