# Generated by Django 4.1.4 on 2022-12-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default-profile.jpg', upload_to='profile_image')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
