# Generated by Django 4.1.4 on 2022-12-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_avatar_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
