# Generated by Django 4.1.4 on 2023-02-13 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
